### ISSUE TITLE
OSX ledger installation instructions give error

### ISSUE THREAD

**Issue by dishmop** [fetchai/docs-archived#14]
I was following these instructions:
https://docs.fetch.ai/getting-started/installation-mac/

Near the beginning, I put this line into the terminal:
cmake -DOPENSSL_ROOT_DIR=/usr/local/ssl -DOPENSSL_LIBRARIES=/usr/local/ssl/lib

and got this error:

CMake Error: The source directory "/Users/diarmidcampbell/Projects" does not appear to contain CMakeLists.txt.

According to Troels the explanation of when/wether to put this line into your terminal is unclear and needs rewording.

**Comment by katharine-murphy** [comment]
OK, I'm going to move this down. An error comes up on the build on Mac if you have not done this. It was not clear to me where to put it either as I found out only during the build process. It seems like you have to go through the build process first before running this command.

**Comment by katharine-murphy** [comment]
OK, I've added this in a separate section 'Possible gotchas' to be clearer.
