### ISSUE TITLE
Bootstrap server

### ISSUE THREAD

**Issue by jones421** [fetchai/docs-archived#198]
Hello @n-hutton and @baykaner

I try to set up a private network of [ledger v1](https://github.com/fetchai/ledger). I cannot understand how to start a bootstrap server and use it for starting the network. I read the [documentation](https://github.com/fetchai/docs/tree/master/docs/ledger_v1) but it does not mention the installation of a bootstrap server. Where can I download the server and how is it setup?

**Comment by 5A11** [comment]
This question is no longer relevant as we have moved to the new ledger v2. See documentation here: https://docs.fetch.ai/ledger_v2/

Please open a new issue if the issue is still there.
