### ISSUE TITLE
Unstaking of FETs on ERC20 contract

### ISSUE THREAD

**Issue by Morhpois01** [fetchai/docs-archived#204]
Hi guys,

I was one of the first guys who staked their FET still on the Etherium blockchain.

Somehow I didn't got the memo that fetch is switching to their own blockchain. And since this moment I didn't got access to the fetch.ai/staking dex and so my FETs are still in the following contract and I don't know how to get them out to convert them to the right blockchain.

Through my Metamask I still can see the transaction that I have sent my FETs to the following contract:
0xaea46A60368A7bD060eec7DF8CBa43b7EF41Ad85

Would be nice if someone could tell how to solve this riddle... 😊 

Cheers
Joe

**Comment by daeMOn63** [comment]
Hi!
Not the best place to reach out for help, you'd have a better time joining our Telegram or Discord channels where lots more people will be able to help you out!

So a quick hint on what happened anyway:
- you had some staked tokens on our ERC20 contract
-  In previous September, we conducted a network upgrade aiming to migrate the funds from this contract to our new mainnet. 
- From here, we had a guide (https://medium.com/fetch-ai/staking-migration-guide-how-to-participate-69a60cb5e2eb) explaining how you could access your funds on the new network.

Have a look at this and see if this works for you, and in case of trouble, reach out for someone on the above channels!

Cheers
