### ISSUE TITLE
Consistent capital titles

### ISSUE THREAD

**Issue by 5A11** [fetchai/docs-archived#276]
### Prerequisites

- [X] My suggestion/issue is about the [latest version of the documentation](https://docs.fetch.ai/).
- [X] I checked the [existing issues](https://github.com/fetchai/docs/issues) to make sure my problem has not already been reported.
- [X] I have read the [code of conduct](https://github.com/fetchai/docs/blob/master/CODE_OF_CONDUCT.md) before creating this issue.

### Project

Something else

### Type

General suggestion

### More details

The section titles need to be consistent in terms of case (capital, lower). Currently they are not.

**Comment by VijaySharma815** [comment]
PR: https://github.com/fetchai/docs/pull/330
