### ISSUE TITLE
External Links Should Open in New Tabs

### ISSUE THREAD

**Issue by VijaySharma815** [fetchai/docs-archived#293]
Internal Links: Links that take users to another page on the same website should open in the same tab user is on.
External Links: Links that take users to a different website should open in new tabs.

**Comment by VijaySharma815** [comment]
@5A11 @bryanchriswhite , seems mkdocs have this feature, we have to upgrade the version of mkdcos 

https://github.com/mkdocs/mkdocs/issues/1958

**Comment by VijaySharma815** [comment]
@5A11 @bryanchriswhite to open external link in a new tab:

`[Ledger (fetchd)](https://github.com/fetchai/fetchd){:target="\_blank"}`

**Comment by VijaySharma815** [comment]
PR with few changes:
https://github.com/fetchai/docs/pull/320

**Comment by JakubAndrysek** [comment]
I have created the plugin to do that automatically. Plugin opens all outgoing links in new tab.
Look at the plugin: [mkdocs-open-in-new-tab](https://github.com/JakubAndrysek/mkdocs-open-in-new-tab).
Demo: https://newtab.kubaandrysek.cz.
